version: "3.8"
services:
  thumbor:
    image: ghcr.io/minimalcompact/thumbor
    container_name: minio-thumbor
    environment:
      # https://github.com/MinimalCompact/thumbor/blob/master/thumbor/conf/thumbor.conf.tpl
      # VIRTUAL_HOST is picked up by nginx-proxy. Here it's set for localhost
      # but you usually need to point it to your domain, e.g. thumbor.example.com
      - VIRTUAL_HOST=localhost
      # THUMBOR_NUM_PROCESSES control how many processes run inside the container
      # Normally this is set in connection with the number of CPU cores
      # Note however that you can also use the docker-compose scale option to dynamically
      # scale your thumbor instances
      - THUMBOR_NUM_PROCESSES=4
      # this would allow CORS from any origin (you can restrict to specific origins if you want)
      - CORS_ALLOW_ORIGIN=*
      # returns a webp image if browser Accept headers match
      - AUTO_WEBP=False
      # nginx-proxy does caching automatically, so no need to store the result storage cache
      # (this greatly speeds up and saves on CPU)
      # - RESULT_STORAGE=thumbor.result_storages.no_storage
      - RESULT_STORAGE_STORES_UNSAFE=True
      - RESULT_STORAGE=tc_redis.result_storages.redis_result_storage
      - RESULT_STORAGE_EXPIRATION_SECONDS=864000
      # - RESULT_STORAGE_FILE_STORAGE_ROOT_PATH=/tmp
      - STORAGE=tc_redis.storages.redis_storage
      - RESPECT_ORIENTATION=True
      - PRESERVE_EXIF_INFO=True
      - HTTP_LOADER_PROXY_HOST="http://10.44.1.129"
      - HTTP_LOADER_PROXY_PORT=8080
      - TC_AWS_REGION=pme-dev
      - TC_AWS_ENDPOINT=http://10.44.1.130:8078
      - TC_AWS_LOADER_BUCKET=mindance-dev
      - TC_AWS_ENABLE_HTTP_LOADER=True
      - LOADER=tc_aws.loaders.s3_loader
      # - Redis setup
      - REDIS_STORAGE_IGNORE_ERRORS=True
      - REDIS_STORAGE_SERVER_PORT=6379
      - REDIS_STORAGE_SERVER_HOST=redis
      - REDIS_STORAGE_SERVER_DB=0
      - REDIS_STORAGE_SERVER_PASSWORD=None
      - REDIS_STORAGE_MODE=single_node
      - REDIS_RESULT_STORAGE_IGNORE_ERRORS=True
      - REDIS_RESULT_STORAGE_SERVER_PORT=6379
      - REDIS_RESULT_STORAGE_SERVER_HOST=redis
      - REDIS_RESULT_STORAGE_SERVER_DB=0
      - REDIS_RESULT_STORAGE_SERVER_PASSWORD=None
      - REDIS_RESULT_STORAGE_MODE=single_node
    volumes:
      # - /Users/docker/thumbor/aws:/app/.aws
      # - /Users/docker/thumbor/cache_storage:/tmp
      - ./data/thumbor/aws:/app/.aws
      - ./data/thumbor/cache_storage:/tmp
    command: pip install --no-cache-dir tc_redis && thumbor
    depends_on:
      - redis
    restart: always
    ports:
      - "8075:80"
    # networks:
    #   - global
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
  redis:
    image: redis:latest
    container_name: thumbor-redis
    ports:
      - "8071:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      # - /Users/docker/thumbor/redis:/data
      - ./data/thumbor/redis:/data

# networks:
#   global:
#     name: global
#     external: true