version: "3.8"
services:
  thumbor:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.9
        WORKDIR /app
        ARG STORAGE \
            REDIS_STORAGE_IGNORE_ERRORS \
            REDIS_STORAGE_SERVER_PORT \
            REDIS_STORAGE_SERVER_HOST \
            REDIS_STORAGE_SERVER_DB \
            REDIS_STORAGE_SERVER_PASSWORD \
            REDIS_STORAGE_MODE \
            REDIS_RESULT_STORAGE_IGNORE_ERRORS \
            RESULT_STORAGE \
            REDIS_RESULT_STORAGE_SERVER_PORT \
            REDIS_RESULT_STORAGE_SERVER_HOST \
            REDIS_RESULT_STORAGE_SERVER_DB \
            REDIS_RESULT_STORAGE_SERVER_PASSWORD \
            REDIS_RESULT_STORAGE_MODE
        ENV STORAGE=${STORAGE} \
            REDIS_STORAGE_IGNORE_ERRORS=${REDIS_STORAGE_IGNORE_ERRORS} \
            REDIS_STORAGE_SERVER_PORT=${REDIS_STORAGE_SERVER_PORT} \
            REDIS_STORAGE_SERVER_HOST=${REDIS_STORAGE_SERVER_HOST} \
            REDIS_STORAGE_SERVER_DB=${REDIS_STORAGE_SERVER_DB} \
            REDIS_STORAGE_SERVER_PASSWORD=${REDIS_STORAGE_SERVER_PASSWORD} \
            REDIS_STORAGE_MODE=${REDIS_STORAGE_MODE} \
            REDIS_RESULT_STORAGE_IGNORE_ERRORS=${REDIS_RESULT_STORAGE_IGNORE_ERRORS} \
            RESULT_STORAGE=${RESULT_STORAGE} \
            REDIS_RESULT_STORAGE_SERVER_PORT=${REDIS_RESULT_STORAGE_SERVER_PORT} \
            REDIS_RESULT_STORAGE_SERVER_HOST=${REDIS_RESULT_STORAGE_SERVER_HOST} \
            REDIS_RESULT_STORAGE_SERVER_DB=${REDIS_RESULT_STORAGE_SERVER_DB} \
            REDIS_RESULT_STORAGE_SERVER_PASSWORD=${REDIS_RESULT_STORAGE_SERVER_PASSWORD} \
            REDIS_RESULT_STORAGE_MODE=${REDIS_RESULT_STORAGE_MODE}
        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
        COPY . .
        CMD ["thumbor"]
    container_name: thumbor
    ports:
      - "8888:8888"
    depends_on:
      - redis
    environment:
      STORAGE: "tc_redis.storages.redis_storage"
      REDIS_STORAGE_IGNORE_ERRORS: True
      REDIS_STORAGE_SERVER_PORT: 6379
      REDIS_STORAGE_SERVER_HOST: "redis"
      REDIS_STORAGE_SERVER_DB: 0
      REDIS_STORAGE_SERVER_PASSWORD: None
      REDIS_STORAGE_MODE: "single_node"
      REDIS_RESULT_STORAGE_IGNORE_ERRORS: True
      RESULT_STORAGE: "tc_redis.result_storages.redis_result_storage"
      REDIS_RESULT_STORAGE_SERVER_PORT: 6379
      REDIS_RESULT_STORAGE_SERVER_HOST: "redis"
      REDIS_RESULT_STORAGE_SERVER_DB: 0
      REDIS_RESULT_STORAGE_SERVER_PASSWORD: None
      REDIS_RESULT_STORAGE_MODE: "single_node"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data
